version: "3.7"

services:
  mongo:
    container_name: gac-mongo
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
    - 27017:27017

  mongo-express:
    container_name: gac-mongo-express
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
    - 8081:8081

  tile-cacher:
    container_name: gac-tile-cacher
    image: nginx:stable
    volumes:
      - ./nginx-tile-cacher.conf:/etc/nginx/conf.d/tile-cacher.conf
    ports:
      - 8082:80
